#!/bin/bash

set -e

export MAKEFLAGS=-j4

UNAME=`uname`

build() {
	make clean

	echo "MUSL_REPO = https://github.com/busterb/musl" > config.mak
	echo "MUSL_VER = git-stealthy-loading" >> config.mak
	echo 'COMMON_CONFIG += CFLAGS="-g0 -Os" CXXFLAGS="-g0 -Os" LDFLAGS="-s"' >> config.mak
	echo "COMMON_CONFIG += --disable-nls" >> config.mak
	echo "GCC_CONFIG += --enable-languages=c,c++" >> config.mak
	echo "GCC_CONFIG += --disable-multilib" >> config.mak

	echo "GCC_CONFIG += --host=x86_64-w64-mingw32" >> config.mak
	echo "CANADIAN := y" >> config.mak

	echo "$2" >> config.mak

	echo Building $1
	make TARGET=$1 > $1.log 2>&1
	echo Installing $1
	make TARGET=$1 install >> $1.log 2>&1
}

if [ ! -e tools/bin -a "$UNAME" == 'Linux' ]; then
	cp config.mak.dist config.mak
	rm -fr tools
	make clean
	make TARGET=i486-linux-musl > toolchain.log 2>&1
	make TARGET=i486-linux-musl install >> toolchain.log 2>&1
	mv output tools
fi

export PATH=`pwd`/tools/bin:$PATH

#build s390x-linux-musl "GCC_CONFIG += --enable-default-pie"
build aarch64-linux-musl "GCC_CONFIG += --enable-default-pie"
build armv5l-linux-musleabi "GCC_CONFIG += --enable-default-pie"
build armv5b-linux-musleabi "GCC_CONFIG += --enable-default-pie"
build i486-linux-musl "GCC_CONFIG += --enable-default-pie"
build x86_64-linux-musl "GCC_CONFIG += --enable-default-pie"
build powerpc-linux-muslsf "GCC_CONFIG += --enable-default-pie"
build powerpc64le-linux-musl "GCC_CONFIG += --enable-default-pie"
build mips64-linux-muslsf "GCC_CONFIG += --enable-default-pie"
build mipsel-linux-muslsf
build mips-linux-muslsf

mv output musl-cross
set +e
find musl-cross/bin -type f -executable |xargs strip
find musl-cross/libexec -type f -executable |xargs strip

zip -r musl-cross musl-cross
